# Generated by Django 5.1.3 on 2024-11-25 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=256, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_expiracion', models.DateField()),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_platillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='platillos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_puntos', models.IntegerField()),
                ('recompensa_puntos', models.IntegerField()),
                ('platillo_dia', models.BooleanField(default=False)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=256)),
                ('total_puntos', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedidos',
            fields=[
                ('id_linea_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total_orden', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_puntos', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='app.pedido')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='app.platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('fecha_caducidad', models.DateField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=256)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='app.pedido')),
            ],
        ),
    ]
