# Generated by Django 5.1.3 on 2024-11-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_platillo_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=256),
        ),
    ]
