# Generated by Django 5.1.3 on 2024-11-25 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='calificacion',
            field=models.IntegerField(default=3, help_text='Calificación del pedido (1 = Muy malo, 5 = Excelente)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
