# Generated by Django 5.1.3 on 2024-11-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mascampos'),
        ('app', '0004_remove_reclamo_estado_remove_reclamo_fecha_and_more'),
    ]

    operations = [
    ]
