# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20241125_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascampos',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
