# Generated by Django 5.1.3 on 2024-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mascampos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascampos',
            name='carnet',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='mascampos',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AlterField(
            model_name='mascampos',
            name='telefono',
            field=models.CharField(default='0000-0000', max_length=9),
        ),
    ]
