# Generated by Django 5.1.3 on 2024-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_clientenoregistrado_alter_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
