# Generated by Django 5.1.3 on 2024-12-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
